CREATE TABLE IF NOT EXISTS affiliates (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS campaigns (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS clicks (
	id SERIAL PRIMARY KEY,
	affiliate_id INTEGER NOT NULL REFERENCES affiliates(id) ON DELETE CASCADE,
	campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
	click_id TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	UNIQUE (affiliate_id, campaign_id, click_id)
);

CREATE TABLE IF NOT EXISTS conversions (
	id SERIAL PRIMARY KEY,
	click_id INTEGER NOT NULL REFERENCES clicks(id) ON DELETE CASCADE,
	amount DOUBLE PRECISION NOT NULL,
	currency TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);